name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'ap-northeast-1' }}

      - name: Install lambroll
        run: |
          curl -sL https://github.com/fujiwara/lambroll/releases/latest/download/lambroll_linux_amd64.tar.gz | tar xz
          mkdir -p $HOME/.local/bin
          mv lambroll $HOME/.local/bin/
          chmod +x $HOME/.local/bin/lambroll

      - name: Initialize Terraform
        run: make tf-init

      - name: Apply Terraform changes
        run: cd terraform && terraform apply -auto-approve

      - name: Deploy
        run: make deploy-all-codebuild
